# Generated by Django 5.2.9 on 2026-01-22 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteleague',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_leagues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favoriteteam',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fixturelineup',
            name='fixture',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lineup', to='sports.fixture'),
        ),
        migrations.AddField(
            model_name='fixturestatistic',
            name='fixture',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistic', to='sports.fixture'),
        ),
        migrations.AddField(
            model_name='league',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='sports.country'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='sports.league'),
        ),
        migrations.AddField(
            model_name='favoriteleague',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='sports.league'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.season'),
        ),
        migrations.AddField(
            model_name='standing',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.league'),
        ),
        migrations.AddField(
            model_name='standing',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.season'),
        ),
        migrations.AddField(
            model_name='headtohead',
            name='team_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='h2h_as_team1', to='sports.team'),
        ),
        migrations.AddField(
            model_name='headtohead',
            name='team_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='h2h_as_team2', to='sports.team'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to='sports.team'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to='sports.team'),
        ),
        migrations.AddField(
            model_name='favoriteteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='sports.team'),
        ),
        migrations.AddField(
            model_name='team',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='sports.venue'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sports.venue'),
        ),
        migrations.AlterUniqueTogether(
            name='favoriteleague',
            unique_together={('user', 'league')},
        ),
        migrations.AlterUniqueTogether(
            name='standing',
            unique_together={('league', 'season')},
        ),
        migrations.AddIndex(
            model_name='headtohead',
            index=models.Index(fields=['team_1', 'team_2'], name='sports_head_team_1__5b411e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='headtohead',
            unique_together={('team_1', 'team_2')},
        ),
        migrations.AlterUniqueTogether(
            name='favoriteteam',
            unique_together={('user', 'team')},
        ),
        migrations.AddIndex(
            model_name='fixture',
            index=models.Index(fields=['date', 'status_short'], name='sports_fixt_date_f38588_idx'),
        ),
    ]
