# Generated by Django 5.2.9 on 2026-01-28 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='leagues',
            field=models.ManyToManyField(blank=True, related_name='teams', to='sports.league'),
        ),
    ]
