# Generated by Django 5.2.9 on 2026-01-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanprofile',
            name='last_inbox_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
