# Generated by Django 5.2.9 on 2026-01-30 21:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('platform', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='apilog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='servermetric',
            options={'get_latest_by': 'timestamp', 'ordering': ['-timestamp']},
        ),
        migrations.RemoveIndex(
            model_name='apilog',
            name='monitoring__timesta_34eb9f_idx',
        ),
        migrations.RemoveIndex(
            model_name='servermetric',
            name='monitoring__timesta_b942f5_idx',
        ),
        migrations.RemoveField(
            model_name='apilog',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='servermetric',
            name='memory_usage',
        ),
        migrations.AddField(
            model_name='apilog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apilog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servermetric',
            name='active_connections',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servermetric',
            name='cache_hits',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servermetric',
            name='cache_misses',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servermetric',
            name='ram_usage',
            field=models.FloatField(default=0.0, help_text='Percentage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apilog',
            name='device_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='level',
            field=models.CharField(default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='servermetric',
            name='cpu_usage',
            field=models.FloatField(help_text='Percentage'),
        ),
        migrations.AlterField(
            model_name='servermetric',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='apilog',
            index=models.Index(fields=['created_at', 'status_code'], name='monitoring__created_3d7179_idx'),
        ),
        migrations.AddIndex(
            model_name='apilog',
            index=models.Index(fields=['endpoint'], name='monitoring__endpoin_fda3e2_idx'),
        ),
    ]
