# Generated by Django 5.2.9 on 2026-01-31 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_guestdevice_alter_apilog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servermetric',
            name='avg_response_time',
            field=models.FloatField(default=0.0, help_text='Avg API Latency in ms for this minute'),
        ),
    ]
