# Generated by Django 5.2.9 on 2026-01-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('event_type', models.CharField(choices=[('MATCH_START', 'Match Start'), ('GOAL', 'Goal'), ('FULL_TIME', 'Full Time'), ('LINEUPS', 'Lineups Confirmed'), ('NEWS', 'News Update'), ('TRANSFER', 'Transfer News'), ('CUSTOM', 'Custom Message')], default='CUSTOM', max_length=50)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='SENT', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('topic', models.CharField(blank=True, max_length=100, null=True)),
                ('audience_label', models.CharField(default='All Users', max_length=100)),
                ('event_type', models.CharField(choices=[('MATCH_START', 'Match Start'), ('GOAL', 'Goal'), ('FULL_TIME', 'Full Time'), ('LINEUPS', 'Lineups Confirmed'), ('NEWS', 'News Update'), ('TRANSFER', 'Transfer News'), ('CUSTOM', 'Custom Message')], default='CUSTOM', max_length=50)),
                ('scheduled_time', models.DateTimeField()),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], default='android', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
