# Generated by Django 5.2.9 on 2026-01-28 21:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='notificationlog',
            name='sent_at',
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='event_type',
            field=models.CharField(default='CUSTOM', max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='topic',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='registration_id',
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['topic', 'created_at'], name='notificatio_topic_d4a983_idx'),
        ),
    ]
