# Generated by Django 5.2.9 on 2026-02-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_userhiddennotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulednotification',
            name='audience_label',
        ),
        migrations.RemoveField(
            model_name='schedulednotification',
            name='topic',
        ),
        migrations.AlterField(
            model_name='schedulednotification',
            name='event_type',
            field=models.CharField(default='CUSTOM', help_text='A string identifier for the app to parse (e.g. NEWS, UPDATE, CUSTOM)', max_length=50),
        ),
    ]
